package view;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Student;
import model.StudentList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */

/**
 *
 * @author maiso
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    DefaultComboBoxModel dm = new DefaultComboBoxModel();
    public static StudentList studentList = new StudentList();
    public static Student student;
    private static DefaultTableModel tblModel = new DefaultTableModel();
    
    public Manager() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Sex = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_City = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jText_StudentIdFilter = new javax.swing.JTextField();
        jButton_Filter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton_Load = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Student = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jText_Subject1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jText_Name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jText_Birthplace = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jText_dateOfBirth = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jText_StudentId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jText_Subject2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jText_Subject3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jText_PhotoPath = new javax.swing.JTextField();
        jButton_ChoosePhoto = new javax.swing.JButton();
        jButton_Insert = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Edit = new javax.swing.JButton();
        jButton_Save = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jButton_Refresh = new javax.swing.JButton();
        buttonGroup_Sex.add(jRadioButton_Male);
        buttonGroup_Sex.add(jRadioButton_Female);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Manager");

        jPanel1.setName("Student Filter"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Student Filter");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("BirthPlace");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("StudentId");

        jButton_Filter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Filter.setText("Filter");
        jButton_Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FilterActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Student List");

        jButton_Load.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Load.setText("Load");
        jButton_Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox_City, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jText_StudentIdFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton_Filter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton_Load, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jText_StudentIdFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Filter)
                    .addComponent(jButton_Load))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Name", "Birthplace", "Dateofbirth", "Sex", "Subject 1", "Subject 2", "Subject 3", "Photo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_StudentMouseClicked(evt);
            }
        });
        jTable_Student.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable_StudentPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Student);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Student Information");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Student Id");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("BirthPlace");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Sex");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("DateOfBirth");

        jRadioButton_Male.setText("Male");

        jRadioButton_Female.setText("Female");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Subject 1");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Subject 2");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Subject 3");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Photo");

        jButton_ChoosePhoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ChoosePhoto.setText("Choose");
        jButton_ChoosePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChoosePhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_Birthplace, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_StudentId)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_Male, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_Female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jText_Subject1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(jText_Subject2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(jText_Subject3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addComponent(jText_PhotoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_ChoosePhoto)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jText_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_Subject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jText_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jText_Subject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jText_Birthplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jText_Subject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jText_PhotoPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ChoosePhoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jRadioButton_Male)
                    .addComponent(jRadioButton_Female))
                .addGap(16, 16, 16))
        );

        jButton_Insert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Insert.setText("Insert");
        jButton_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertActionPerformed(evt);
            }
        });

        jButton_Delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Edit.setText("Edit");
        jButton_Edit.setActionCommand("");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Save.setText("Save");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Exit.setText("Exit");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jButton_Refresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Refresh.setText("Refresh");
        jButton_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Insert, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton_Edit, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton_Save, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jButton_Refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Insert)
                    .addComponent(jButton_Delete)
                    .addComponent(jButton_Edit)
                    .addComponent(jButton_Save)
                    .addComponent(jButton_Exit))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jText_StudentId.getText().trim());
        String name = jText_Name.getText();
        String cityName = jText_Birthplace.getText().trim();
        String[] cities = setCity();
        int cityIndex = 0;
        for(int i = 1; i < cities.length; i++){
            if(cities[i].equals(cityName)){
                cityIndex = i;
            }
        }
        City city = new City(cityIndex,cityName);
        String dob = jText_dateOfBirth.getText();
        String sex;
        if(jRadioButton_Male.isSelected()){
            sex = "Male";
        }
        else{
            sex = "Female";
        }
        float subject1 = Float.parseFloat(jText_Subject1.getText());
        float subject2 = Float.parseFloat(jText_Subject2.getText());
        float subject3 = Float.parseFloat(jText_Subject3.getText()); 
        File imagePath = new File(jText_PhotoPath.getText().trim());
        String photo = encode(imagePath);
        
        student = new Student(id, name, city, dob, sex, subject1, subject2, subject3,photo);
        if(!studentList.containStudent(student)){
             studentList.addStudent(student);
        
            //store data into string array
            String[] data = {jText_StudentId.getText(),jText_Name.getText(),city.getCityName(),dob,sex,jText_Subject1.getText(),jText_Subject2.getText(),jText_Subject3.getText(),photo};

            // add string data
            tblModel = (DefaultTableModel) jTable_Student.getModel();
            tblModel.addRow(data);

            // show success message
            JOptionPane.showMessageDialog(this, "Insert successfully !");


            //clear text field
            jText_StudentId.setText("");
            jText_Name.setText("");
            jText_Birthplace.setText("");
            jText_dateOfBirth.setText("");
            jText_Subject1.setText("");
            jText_Subject2.setText("");
            jText_Subject3.setText("");
            jText_PhotoPath.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "Student is already exists. Check information", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
        
    }//GEN-LAST:event_jButton_InsertActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        
        //get Jtable model
       tblModel = (DefaultTableModel) jTable_Student.getModel();
       
       int returnValue = JOptionPane.showConfirmDialog(this, "Are you sure ?","Delete",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if(returnValue == JOptionPane.YES_OPTION){
                //delete row
            if(jTable_Student.getSelectedRowCount()>0){
                    int rowSelected = jTable_Student.getSelectedRow();
                    String rowSelectedData = (String) jTable_Student.getModel().getValueAt(rowSelected, 0);
                    int deleteId = Integer.parseInt(rowSelectedData);
                    studentList.removeStudent(deleteId);
                    tblModel.removeRow(jTable_Student.getSelectedRow());
                    
                    //clear text field
                    jText_StudentId.setText("");
                    jText_Name.setText("");
                    jText_Birthplace.setText("");
                    jText_dateOfBirth.setText("");
                    jText_Subject1.setText("");
                    jText_Subject2.setText("");
                    jText_Subject3.setText("");
             }
           
       }
       
       
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        // TODO add your handling code here:
        
        Detail de = new Detail();
        de.setVisible(true);
       
    }//GEN-LAST:event_jButton_EditActionPerformed
    public static Student getStudent(){
        return student;
    }
    
    public static StudentList getStudentList(){
        return studentList;
    }
    private void jTable_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_StudentMouseClicked
        // TODO add your handling code here:
            int selectedRow = jTable_Student.getSelectedRow();
            String studentId = (String) jTable_Student.getModel().getValueAt(selectedRow,0);
            String name = (String) jTable_Student.getModel().getValueAt(selectedRow,1);
            
            String birthPlace = (String) jTable_Student.getModel().getValueAt(selectedRow,2);
            String[] cities = setCity();
            int cityIndex = 0;
            for(int i = 1; i < cities.length; i++){
                if(cities[i].equals(birthPlace)){
                    cityIndex = i;
                    break;
                }
            }
            City city = new City(cityIndex, birthPlace);
            String dateOfBirth = (String)jTable_Student.getModel().getValueAt(selectedRow,3);
            String sex = (String)jTable_Student.getModel().getValueAt(selectedRow,4);
            String subject1 = (String)jTable_Student.getModel().getValueAt(selectedRow,5);
            String subject2 = (String)jTable_Student.getModel().getValueAt(selectedRow,6);
            String subject3 = (String)jTable_Student.getModel().getValueAt(selectedRow,7);
            String photo = (String)jTable_Student.getModel().getValueAt(selectedRow, 8);
            
            
            student = new Student(Integer.parseInt(studentId), name, city, dateOfBirth, sex, Float.parseFloat(subject1),  Float.parseFloat(subject2),  Float.parseFloat(subject3),photo);
            
            jText_StudentId.setText(studentId);
            jText_Name.setText(name);
            jText_Birthplace.setText(birthPlace);
            jText_dateOfBirth.setText(dateOfBirth);
            if(sex.equals("Male")){
                jRadioButton_Male.setSelected(true);
            }
            else{
                jRadioButton_Female.setSelected(true);
            }
            jText_Subject1.setText(subject1);
            jText_Subject2.setText(subject2);
            jText_Subject3.setText(subject3);
    }//GEN-LAST:event_jTable_StudentMouseClicked

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("E:\\Java\\Project\\Student_Manager\\src");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnValue = fileChooser.showSaveDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            File saveFile = new File(path);
            try {
                if(!saveFile.exists()){
                    saveFile.createNewFile();
                }
                FileOutputStream fos = new FileOutputStream(saveFile,false);
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                ArrayList<Student> students = studentList.displayStudentList();
                for(Student s: students){
                   oos.writeObject(s);
                   oos.flush();
                }
                JOptionPane.showMessageDialog(this, "Saved successfully");
                
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Cannot save");
                
            }
           
            
            
            
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton_LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoadActionPerformed
        // TODO add your handling code here:
        try {
           
            studentList = new StudentList();
            JFileChooser fileChooser = new JFileChooser("E:\\Java\\Project\\Student_Manager\\src");
            fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            int returnValue = fileChooser.showOpenDialog(this);
            if(returnValue == JFileChooser.APPROVE_OPTION){
                String path = fileChooser.getSelectedFile().getAbsolutePath();
                File loadFile = new File(path);
                FileInputStream fis = new FileInputStream(loadFile);
                ObjectInputStream ois = new ObjectInputStream(fis);
                while(fis.available() > 0){
                    Student s = (Student) ois.readObject();
                    studentList.addStudent(s);
                }
                tblModel = (DefaultTableModel) jTable_Student.getModel();
                tblModel.setRowCount(0);

                ArrayList<Student> students = studentList.displayStudentList();
                for(Student s : students){
                    int studentId = s.getStudentId();
                    String studentName = s.getStudentName();
                    String c = s.getCity().getCityName();
                    String d = s.getDateOfBirth();

                    String m = s.getSex();
                    float s1 = s.getSubject1();
                    float s2 = s.getSubject2();
                    float s3 = s.getSubject3();
                    String photo = s.getPhoto();

                    String[] data = {studentId+"",studentName,c,d,m,s1+"",s2+"",s3+"",photo};
                    tblModel = (DefaultTableModel) jTable_Student.getModel();
                    tblModel.addRow(data);
                }
            
            }
        } catch (HeadlessException | FileNotFoundException e) {
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_LoadActionPerformed

    private void jButton_FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FilterActionPerformed
        // TODO add your handling code here:
        tblModel = (DefaultTableModel) jTable_Student.getModel();
        tblModel.setRowCount(0);
        
        
            String city = (String) jComboBox_City.getSelectedItem();
            if(city != null){
                ArrayList<Student> studentsFromSameCity = studentList.filterStudentByCity(city);
                for(Student s : studentsFromSameCity){
                    int studentId = s.getStudentId();
                    String studentName = s.getStudentName();
                    String c = s.getCity().getCityName();
                    String d = s.getDateOfBirth();

                    String m = s.getSex();
                    float s1 = s.getSubject1();
                    float s2 = s.getSubject2();
                    float s3 = s.getSubject3();
                    String photo = s.getPhoto();

                    String[] data = {studentId+"",studentName,c,d,m,s1+"",s2+"",s3+"",photo};
                    tblModel = (DefaultTableModel) jTable_Student.getModel();
                    tblModel.addRow(data);
                }
            }
            else if(jText_StudentIdFilter.getText() != null){
                int id = Integer.parseInt(jText_StudentIdFilter.getText());
                Student result = studentList.filterStudentById(id);
                int studentId = result.getStudentId();
                String studentName = result.getStudentName();
                String c = result.getCity().getCityName();
                String d = result.getDateOfBirth();

                String m = result.getSex();
                float s1 = result.getSubject1();
                float s2 = result.getSubject2();
                float s3 = result.getSubject3();
                String photo = result.getPhoto();

                String[] data = {studentId+"",studentName,c,d,m,s1+"",s2+"",s3+"",photo};
                tblModel = (DefaultTableModel) jTable_Student.getModel();
                tblModel.addRow(data);
                
            }
            //clear text field
                    jText_StudentId.setText("");
                    jText_Name.setText("");
                    jText_Birthplace.setText("");
                    jText_dateOfBirth.setText("");
                    jText_Subject1.setText("");
                    jText_Subject2.setText("");
                    jText_Subject3.setText("");
            
        
        
    }//GEN-LAST:event_jButton_FilterActionPerformed

    private void jButton_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshActionPerformed
        // TODO add your handling code here:
            tblModel = (DefaultTableModel) jTable_Student.getModel();
            tblModel.setRowCount(0);
        
            
            ArrayList<Student> students = studentList.displayStudentList();
            for(Student s : students){
                int studentId = s.getStudentId();
                String studentName = s.getStudentName();
                String c = s.getCity().getCityName();
                String d = s.getDateOfBirth();

                String m = s.getSex();
                float s1 = s.getSubject1();
                float s2 = s.getSubject2();
                float s3 = s.getSubject3();
                String photo = s.getPhoto();

                String[] data = {studentId+"",studentName,c,d,m,s1+"",s2+"",s3+"",photo};
                tblModel = (DefaultTableModel) jTable_Student.getModel();
                tblModel.addRow(data);
            }
    }//GEN-LAST:event_jButton_RefreshActionPerformed

    private void jButton_ChoosePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChoosePhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("E:\\Java\\Project\\Student_Manager\\src");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnValue = fileChooser.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            jText_PhotoPath.setText(path); 
        }
    }//GEN-LAST:event_jButton_ChoosePhotoActionPerformed

    private void jTable_StudentPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable_StudentPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable_StudentPropertyChange

    public static String encode(File picture){
        String base64 = "";
        try {
            if(picture != null){
                 byte[] decodedByte = Files.readAllBytes(Path.of(picture.getAbsolutePath()));
                base64 = Base64.getEncoder().encodeToString(decodedByte);
            }
           
        } catch (IOException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        return base64;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
                setCity();
                
                
            }
        });
       
        
        
        
        
        
       
    }

    
    public static String[] setCity(){
        File cityFile = new File("E:\\Java\\Project\\Student_Manager\\src\\city.txt");
        String[] city = new String[64];
        
        try {
            FileInputStream fis = new FileInputStream(cityFile);
            InputStreamReader streamReader = new InputStreamReader(fis,"utf8");
            BufferedReader br = new BufferedReader(streamReader);
            String lines;
            
            int i = 1;
            while((lines = br.readLine()) != null){
                lines = lines.substring(2).trim();
                city[i] = lines;
                i++;
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel dm = new DefaultComboBoxModel<>(city);
        jComboBox_City.setModel(dm);
        return city;
        
        
    }
    
   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.ButtonGroup buttonGroup_Sex;
    private javax.swing.JButton jButton_ChoosePhoto;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Filter;
    private javax.swing.JButton jButton_Insert;
    private javax.swing.JButton jButton_Load;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JButton jButton_Save;
    private static javax.swing.JComboBox<String> jComboBox_City;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JRadioButton jRadioButton_Female;
    private static javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable_Student;
    private static javax.swing.JTextField jText_Birthplace;
    private static javax.swing.JTextField jText_Name;
    private javax.swing.JTextField jText_PhotoPath;
    private static javax.swing.JTextField jText_StudentId;
    private javax.swing.JTextField jText_StudentIdFilter;
    private static javax.swing.JTextField jText_Subject1;
    private static javax.swing.JTextField jText_Subject2;
    private static javax.swing.JTextField jText_Subject3;
    private static javax.swing.JTextField jText_dateOfBirth;
    // End of variables declaration//GEN-END:variables

}
